name: Create Infra 


on:
  push:
   branches: ["develop"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  plan-dev: 
    name: 'terraform plan dev'
    runs-on: ubuntu-latest
    env: 
      TF_WORKING_DIR: "main/infra"

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
          
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true    

      - name: Terraform Init
        id: init
        run: terraform init -backend=true -backend-config="config/dev/config.hcl"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color    
 
      - name: Terraform Plan
        id: plandev
        run: terraform plan -no-color -var-file="config/dev/terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="config/dev/terraform.tfvars"